### ISSUE TITLE
建议使用有道词典的语音

### ISSUE THREAD

**Issue by vaaandark** [Dramalf/GRE3000-cli#1]
可以对比一下 hello 的读音：
- [sogo](https://fanyi.sogou.com/reventondc/synthesis?text=hello&speed=1&lang=enS&from=translateweb&speaker=5)
- [youdao](https://dict.youdao.com/dictvoice?audio=hello&type=1)

感觉搜狗的发音机器感很明显，像是直接套用的模型，我个人认为有道的比较好。

`https://dict.youdao.com/dictvoice?audio=${word}&type=${type}`

`type` 为 1 时是英式，为 2 时是美式

**Comment by Dramalf** [comment]
好的，我看看

**Comment by Dramalf** [comment]
已经换成有道的服务了
